### ISSUE TITLE
error = "r[e.serviceid] is undefined"

### ISSUE THREAD

**Issue by psiho-fab** [grafana/grafana-zabbix#1490] opened 2022-08-24 13:37 UTC
zabbix = 6.0.7
grafana = 9.1.1
Zabbix plugin for Grafana = 4.2.9

dataSource = Zabbix
QueryMode = IT Services
IT Service = Web_Site, Property = SLA (or Status)
error = "r[e.serviceid] is undefined"
data = "No data"

![image](https://user-images.githubusercontent.com/79001224/186432068-6a6f13ca-e2e7-4eb3-b32e-d7fca411ae6c.png)

**Comment by andreisolo0** [comment] 2022-09-19 12:29
Same issue here. Any idea what's the cause? I can see the services defined if I query after their name but they do not appear on the droplist. For those that appear in the droplist query works

**Comment by bhrbgk** [comment] 2022-11-30 13:28
Hello, same problem here!!!
Pls say thereis a fix for this - a have a very annoying customer that borthers me weekly ^^ 
Best Regards!

**Comment by bhrbgk** [comment] 2023-01-25 09:59
Hello!
Any workarrounds regarding this issue? 
we also have a customer that bothers regularily! Thanks for your help

**Comment by alexanderzobnin** [comment] 2023-03-22 10:17
Could you check it against 4.3 release? It supports new IT services in Zabbix.

**Comment by bhrbgk** [comment] 2023-03-23 07:13
Hi Alex, 
Good news: The serviceid error is gone!! Thank you!
Bad news: 
When we now try to edit/add a dashboard variable:
```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=%5Bobject%20Promise%5D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

    at Tr (https://example.com/grafana/public/plugins/alexanderzobnin-zabbix-app/datasource/module.js:85:4227)
    at div
    at div
    at c (https://example.com/grafana/public/build/8534.e679449576cebd9f6b2c.js:1475:20)
    at ah (https://example.com/grafana/public/build/8534.e679449576cebd9f6b2c.js:9779:22630)
    at xt (https://example.com/grafana/public/build/215.c1c0320c66de376bf22b.js:154:127638)
    at form
    at Se (https://example.com/grafana/public/build/8534.e679449576cebd9f6b2c.js:5963:4630)
    at xt (https://example.com/grafana/public/build/215.c1c0320c66de376bf22b.js:154:127638)
    at div
    at div
    at div
    at div
    at ne (https://example.com/grafana/public/build/215.c1c0320c66de376bf22b.js:125:13314)
    at r (https://example.com/grafana/public/build/8534.e679449576cebd9f6b2c.js:475:3184)
    at div
    at div
    at div
    at W (https://example.com/grafana/public/build/8534.e679449576cebd9f6b2c.js:4884:2944)
    at bt (https://example.com/grafana/public/build/8534.e679449576cebd9f6b2c.js:5991:740)
    at xt (https://example.com/grafana/public/build/215.c1c0320c66de376bf22b.js:154:127638)
    at ga (https://example.com/grafana/public/build/8534.e679449576cebd9f6b2c.js:6010:11767)
    at nt (https://example.com/grafana/public/build/DashboardPage.087f9a0f47b10fa8da52.js:387:424)
    at DashboardPage
    at xt (https://example.com/grafana/public/build/215.c1c0320c66de376bf22b.js:154:127638)
    at Suspense
    at i (https://example.com/grafana/public/build/8534.e679449576cebd9f6b2c.js:1270:169)
    at dm (https://example.com/grafana/public/build/8534.e679449576cebd9f6b2c.js:9734:330)
    at Kt (https://example.com/grafana/public/build/215.c1c0320c66de376bf22b.js:158:13496)
    at Kt (https://example.com/grafana/public/build/215.c1c0320c66de376bf22b.js:158:15691)
    at main
    at Uu (https://example.com/grafana/public/build/8534.e679449576cebd9f6b2c.js:9695:2479)
    at Kt (https://example.com/grafana/public/build/215.c1c0320c66de376bf22b.js:158:9783)
    at div
    at d (https://example.com/grafana/public/build/8534.e679449576cebd9f6b2c.js:2525:4092)
    at p (https://example.com/grafana/public/build/215.c1c0320c66de376bf22b.js:32:52076)
    at i (https://example.com/grafana/public/build/8534.e679449576cebd9f6b2c.js:5204:16801)
    at i (https://example.com/grafana/public/build/8534.e679449576cebd9f6b2c.js:1270:169)
    at f (https://example.com/grafana/public/build/8534.e679449576cebd9f6b2c.js:1270:720)
    at S (https://example.com/grafana/public/build/215.c1c0320c66de376bf22b.js:154:125332)
    at Bm (https://example.com/grafana/public/build/8534.e679449576cebd9f6b2c.js:9747:122)
    ```
    
We are currently on grafana verion `9.4.3`.  Cloud try to downgrade though. What version would you recommend? 

Best Regards!!!

**Comment by zoltanbedi** [comment] 2023-10-19 12:24
This should not be an issue anymore. If you still see this let us know please.

**Closed by zoltanbedi** 2023-10-19 12:24 UTC
Labels: state: need more info
