### ISSUE TITLE
Problem when Trying to Use the "Problems" Query Type

### ISSUE THREAD

**Issue by LinekerCalseverini** [grafana/grafana-zabbix#1834] opened 2024-06-05 13:23 UTC
When I select the "Problems" Query Type it throws the following error:
`Invalid params. Invalid parameter "/output/2": value must be one of "proxyid", "name", "proxy_groupid", "local_address", "local_port", "operating_mode", "allowed_addresses", "address", "port", "description", "tls_connect", "tls_accept", "tls_issuer", "tls_subject", "custom_timeouts", "timeout_zabbix_agent", "timeout_simple_check", "timeout_snmp_agent", "timeout_external_check", "timeout_db_monitor", "timeout_http_agent", "timeout_ssh_agent", "timeout_telnet_agent", "timeout_script", "timeout_browser", "lastaccess", "version", "compatibility", "state".`

The API is sending this body to the zabbix API:
{"datasourceId":2,"method":"proxy.get","params":{"output":["proxyid","host"]}}

I'm pretty sure the problem is because in the new Zabbix Version, there's a new proxy table, and this also changed how the proxy.get procedure call works, since the proxy object now doesn't have a field called "host" (it was changed for "name", see [Zabbix 7.0 Proxy Object](https://www.zabbix.com/documentation/current/en/manual/api/reference/proxy/object))

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 10.4.2   | 7.0.0  | 4.4.9                 |

**Comment by zoltanbedi** [comment] 2024-06-05 13:40
duplicate of https://github.com/grafana/grafana-zabbix/issues/1714

**Closed by zoltanbedi** 2024-06-05 13:40 UTC

**Comment by fabio-oliveira-efeo** [comment] 2024-06-05 17:47
@LinekerCalseverini As it was changed from 'host' to 'name', can we find it in the code to test as a temporary fix? I know we are looking for a quick solution and maybe they will resolve it quickly in a new release of the plugin. My fear is that it will take time to fix it.

**Comment by LinekerCalseverini** [comment] 2024-06-05 22:35
@fabio-oliveira-efeo 

Yeah, that should work. Would recommend backing up the module.js file and restarting the Grafana server.

**Comment by intan-it** [comment] 2024-06-06 14:56
> @fabio-oliveira-efeo
> 
> Yeah, that should work. 

Unfortunately, after editing module.js, the plugin is disabled due to "Modified signature".

**Comment by LinekerCalseverini** [comment] 2024-06-06 14:59
@intan-it You can change the "allow_loading_unsigned_plugins" to allow the plugin to be enabled.
For the signature, you have to edit the plugin.json and comment the "build" attribute.

Then restart Grafana server.

**Comment by intan-it** [comment] 2024-06-07 06:27
> @intan-it 

Excuse me :)
I understand "allow_loading_unsigned_plugins" and "restart Grafana server" - it is obvious.
But I am stuck on "edit plugin.json and comment the "build" attribute". Should I create a new hash or just change the build number?

P.S. Thanks for your time.

**Comment by DonPook** [comment] 2024-06-07 09:50
> > @intan-it
> 
> Excuse me :) I understand "allow_loading_unsigned_plugins" and "restart Grafana server" - it is obvious. But I am stuck on "edit plugin.json and comment the "build" attribute". Should I create a new hash or just change the build number?
> 
> P.S. Thanks for your time.

For me the plugin.json was here and it allowed me to start the application: 

/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/plugin.json 

The issue I have now, is that I don't see the "Zabbix Problems" visualization and it only returns the alerts in a table. Any clue why I lost the visualizations?

**Comment by LinekerCalseverini** [comment] 2024-06-07 15:06
@DonPook The Zabbix Problems visualization doesn't work in Table view (the panel option), it works in the List view (the one that has a broken heart icon).

Unfortunately, I have not found a way to circumvent this.

**Comment by mdubell** [comment] 2024-06-08 11:40
I used the following steps to modify this plugin and restore functionality with Zabbix 7.0 . 

1) Add the following line to /etc/grafana/grafana.ini to allow unsigned plugins to be loaded.
     allow_loading_unsigned_plugins = alexanderzobnin-zabbix-app,alexanderzobnin-zabbix-datasource,alexanderzobnin-zabbix-triggers-panel
     
2) Remove the digital signature from the grafana-zabbix plugin. Grafana will never load modified plugins that are signed
     mv /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/MANIFESST.txt   ~/ 
	
3) Edit /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource/module.js
     Changes:
           _{output:["proxyid","host"]}_ to _{output:["proxyid","name"]}_

If you're using the Zabbix Problems visualization with the Table Layout the following modification was needed to remove the error "Invalid params. Invalid parameter "/selectUsers": an array or a character string is expected." when an alert line is expanded. 

4) Edit /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource/module.js
     Changes:
          _getEventAlerts(e){const t={eventids:e,output:["alertid","eventid","message","clock","error"],selectUsers:!0}_ to 
          _getEventAlerts(e){const t={eventids:e,output:["alertid","eventid","message","clock","error"],selectUsers:"extend"}_
     
5) Restart grafana-server service
