### ISSUE TITLE
Invalid params. Invalid parameter "/": the parameter "host" is missing.

### ISSUE THREAD

**Issue by clibon** [grafana/grafana-zabbix#1787] opened 2024-02-05 19:03 UTC
**Describe the bug**
Upon upgrading to the latest versions of Zabbix, Grafana and Grafana-zabbix plugin, I am encountering the following error on all panels whose datasource is zabbix:

Invalid params. Invalid parameter "/": the parameter "host" is missing.

Appreciate your help on this topic as all our dashboards are currently not working.

**Expected behavior**
Dashboard and exploring zabbix data should be successful

**Screenshots**
The following error is displayed when a dashboard is loaded and also when the 'Save and Test' button within the zabbix datasource configuration page is selected.
![image](https://github.com/grafana/grafana-zabbix/assets/95121299/88e04729-40b9-4bb4-b8fc-125cab7defd1)

**Network data**

![image](https://github.com/grafana/grafana-zabbix/assets/95121299/440dfa89-ba16-40a3-b385-dab4785ebeb9)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 10.3.1  | 6.4.11  | 4.4.5                 |

**Comment by gabor** [comment] 2024-02-12 13:38
hi @clibon , could you describe for us how to reproduce the issue? does this happen in explore too? could you describe a minimal query that triggers this error?

**Comment by clibon** [comment] 2024-02-12 20:03
Hi @gabor. The problem also happens within the explore tool and what we noted is that post upgrade the error message is displayed every time a query or test connection is performed against the grafana-zabbix plugin.

Unfortunately I cannot provide the exact query as in the meantime we have reverted back to an older spec since it was affecting production tools. Thanks for your query.

**Comment by gabor** [comment] 2024-02-14 12:26
@clibon thanks for the info.. just to clarify, which component(s) did you revert to fix the problem?
- grafana?
- grafana zabbix plugin?
- zabbix?

**Comment by clibon** [comment] 2024-02-14 20:21
Hi @gabor. We actually had to revert the complete VM to a snapshot taken before the upgrade started.

As when we attempted to downgrade grafana or the grafana-zabbix plugin, both resulted in the same error.

By reverting back we are now fully operational once again.

**Comment by gabor** [comment] 2024-02-15 11:13
i see, thanks for the info 👍 .unfortunately i am not able to reproduce the issue, so we'll have to close the issue. if you find any more info in the future, just reply here, and we can reopen the issue.

**Comment by clibon** [comment] 2024-03-14 08:35
Hi,

we came across the same issue, this time using the following component versions:

Zabbix: 6.4.12
Grafana: 10.4.0
Grafana-Zabbix Plugin: 4.4.6

Could you kindly assist?

Thanks.

**Comment by clibon** [comment] 2024-03-16 14:58
Upon further investigations, I noticed that following behaviour when selecting the 'Save & test' button on the data source page. All dumps taken from Chrome's developer mode:

This request works fine:

Payload ->
![image](https://github.com/grafana/grafana-zabbix/assets/95121299/3f079696-e38a-49c1-ab5e-0a26af7d8ad1)

Response ->
![image](https://github.com/grafana/grafana-zabbix/assets/95121299/2aa00829-d52c-487c-8658-e6ccad131e6e)

From now onwards, exceptions are reported from the Zabbix-API:

**Request 1:**
Payload ->
![image](https://github.com/grafana/grafana-zabbix/assets/95121299/92991d06-1fee-48df-8ef6-914b33cd46bc)

Response ->
![image](https://github.com/grafana/grafana-zabbix/assets/95121299/7b8a199c-5ed3-4fde-b7a7-7921b72c6e6b)

**Request 2:**
Payload ->
![image](https://github.com/grafana/grafana-zabbix/assets/95121299/b0deb28e-751d-4e21-88e6-bf49d3709763)

Response ->
![image](https://github.com/grafana/grafana-zabbix/assets/95121299/fd7023ef-9307-4420-96c9-8b66b8607eff)

**Comment by clibon** [comment] 2024-03-19 09:11
UPDATE: The issue has now been resolved as follows.

The grafana user on zabbix was not part of any group, so we created a new group called API Group and gave read-only access to the hosts.

Issue can be closed and thanks.

**Comment by gabor** [comment] 2024-03-27 14:20
i'm glad it worked out at the end. closing issue as requested.

**Closed by gabor** 2024-03-27 14:20 UTC
