### ISSUE TITLE
win10  plugin unavailable issue

### ISSUE THREAD

**Issue by hejunv** [grafana/grafana-zabbix#1673] opened 2023-08-22 08:22 UTC
**Describe the bug**
I am installing grafana on win10 system. installing zabbix plugin is encountering plugin unavailable issue. What should I do to fix this issue please? Thanks for your help.
**Expected behavior**
Installing the plugin using all of the methods doesn't work。
**Screenshots**
 plugin unavailable

**Network data**
If it's related to metric data visualization would be great to get the raw query and response for the network request (check this in browser dev tools network tab, there you can see metric requests, please include the request body and request response)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | --5.0---- | --------------------- |
| 10.0.3   | 5.0  | 4.3.1                |

**Comment by hejunv** [comment] 2023-08-22 08:25
logger=context userId=1 orgId=1 uname=admin t=2023-08-22T16:23:43.5977839+08:00 level=warn msg="Plugin unavailable" error="plugin unavailable" traceID=
logger=context userId=1 orgId=1 uname=admin t=2023-08-22T16:23:43.5977839+08:00 level=error msg="Request Completed" method=POST path=/api/datasources/1/resources/zabbix-api status=503 remote_addr=127.0.0.1 time_ms=1 duration=1.35ms size=46 referer=http://127.0.0.1:3000/datasources/edit/ad90a24a-c970-4431-bab8-256decab74d9 handler=/api/datasources/:id/resources/*

**Comment by hejunv** [comment] 2023-08-22 08:25
logger=context userId=1 orgId=1 uname=admin t=2023-08-22T16:23:43.5977839+08:00 level=warn msg="Plugin unavailable" error="plugin unavailable" traceID=
logger=context userId=1 orgId=1 uname=admin t=2023-08-22T16:23:43.5977839+08:00 level=error msg="Request Completed" method=POST path=/api/datasources/1/resources/zabbix-api status=503 remote_addr=127.0.0.1 time_ms=1 duration=1.35ms size=46 referer=http://127.0.0.1:3000/datasources/edit/ad90a24a-c970-4431-bab8-256decab74d9 handler=/api/datasources/:id/resources/*

**Comment by UnicodeTreason** [comment] 2023-08-25 07:13
Ahoy hoy,
Yeah that error message is super vague. I had a similar issue when running Grafana in a docker container and the root cause was permissions.

I was able to get the correct permissions by simply letting Grafana install the plugin, rather than me unzipping and copying it in myself.

`grafana-cli plugins install alexanderzobnin-zabbix-app`

**Comment by alexanderzobnin** [comment] 2023-08-29 15:21
Closing this in favor of #1604

**Closed by alexanderzobnin** 2023-08-29 15:21 UTC
