### ISSUE TITLE
replaceAlias function get ignored when Dashboard Transforms like "Join by label" are applied on the dashboard

### ISSUE THREAD

**Issue by samu6851** [grafana/grafana-zabbix#1816] opened 2024-04-13 21:15 UTC
**Describe the bug**
The replaceAlias function get ignored when Dashboard Transforms like "Join by label" are applied on the dashboard.

**Expected behavior**
I would expect the function to keep working.

**Screenshots**
![image](https://github.com/grafana/grafana-zabbix/assets/23225448/1a173f32-7d9d-42ff-a43a-afc93507d423)
![image](https://github.com/grafana/grafana-zabbix/assets/23225448/2ccf9e84-6ca0-4bfb-bbed-1b91d2ccf943)

**Network data**
If it's related to metric data visualization would be great to get the raw query and response for the network request (check this in browser dev tools network tab, there you can see metric requests, please include the request body and request response)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| v11.1.0  | n/a  | 4.4.6                 |

[PanelDebugSnapshotDashboard.txt](https://github.com/grafana/grafana-zabbix/files/14968663/PanelDebugSnapshotDashboard.txt)

Created this issue via the request made here: https://raintank-corp.slack.com/archives/C04J73AAQ87/p1712859211221999

Here is the link to the mentioned PR: https://github.com/grafana/grafana-zabbix/pull/1813/files

**Comment by zoltanbedi** [comment] 2024-05-08 14:56
duplicate of #1812

**Closed by zoltanbedi** 2024-05-08 14:56 UTC
