### ISSUE TITLE
Zabbix 7.2 API Authentication Changes Cause Plugin Incompatibility

### ISSUE THREAD

**Issue by albertofreire** [grafana/grafana-zabbix#1929] opened 2024-12-11 06:14 UTC
With the release of Zabbix version 7.2, the API authentication method has been altered. As a result, the alexanderzobnin-zabbix-datasource plugin is not compatible with the new authentication mechanism, leading to errors when attempting to query data.

Steps to Reproduce:
Upgrade Zabbix to version 7.2.
Configure the alexanderzobnin-zabbix-datasource plugin with the existing settings.
Attempt to retrieve data through the plugin.

Actual Behavior:
Authentication fails, and data queries result in errors due to unexpected parameters.

**Error Log:**
```
logger=plugin.alexanderzobnin-zabbix-datasource 
t=2024-12-11T02:35:20.245207327-03:00 
level=error 
msg="Partial data response error" 
endpoint=queryData 
error="Invalid request. Invalid parameter \"/\": unexpected parameter \"auth\"." 
pluginId=alexanderzobnin-zabbix-datasource 
status=500 
dsName="Zabbix" 
dsUid=fe06c328-44d9-4926-b657-1a410e3d73a1 
statusSource=plugin 
uname="XXXXX" 
refID=D
```

Additional Information:
https://www.zabbix.com/documentation/7.2/en/manual/api/#authorization-methods

**Comment by alxcreate** [comment] 2024-12-11 07:12
https://github.com/grafana/grafana-zabbix/issues/1914

**Comment by alxcreate** [comment] 2024-12-11 07:12
Duplicate of #1914

**Closed** 2024-12-12 14:30 UTC
Labels: type: duplicate
