### ISSUE TITLE
plugin unavailable

### ISSUE THREAD

**Issue by aureoinacio** [grafana/grafana-zabbix#1675] opened 2023-08-27 17:06 UTC

**Comment by rasmuslindendk** [comment] 2023-08-27 22:18
Well thats a pretty terrible error description, i wonder if this is the same issue as i am experience here.
On a fresh zabbix installation:

I am currently fighting to get the zabbix plugin to load.

**OS**
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

**GRAPHANA**
Graphana  version : Version 10.1.0 (commit: 838218ba20, branch: HEAD)

**PLUGIN**
Version 4.3.1 - get data, but dashboards does not work
Versopn 4.4.0 - Plugin unavailable

I cannot seem to find a combination on where dashboards work, and the zabbix data source pulls data.
On 4.3.1 there is no issue getting data, however dashboards (datasource okj, reports Zabbix API version: 6.4.0, DB connector type: postgres)
On 4.4.0 reports Plugin unavailable

Anybody has any suggestions, would be greatly appriciated.

**Comment by CharlesCage** [comment] 2023-08-28 00:29
I also ran into a similar issue upon 10.1.0 upgrade. I'm seeing the following:

`Aug 27 19:28:09 dashboard grafana[9755]: logger=plugin.alexanderzobnin-zabbix-datasource t=2023-08-27T19:28:09.810413812-05:00 level=error msg="plugin process exited" path=/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/gpx_zabbix-plugin_linux_amd64 pid=9763 error="exit status 1"
Aug 27 19:28:09 dashboard grafana[9755]: logger=plugin.loader t=2023-08-27T19:28:09.810607238-05:00 level=error msg="Could not start plugin" pluginId=alexanderzobnin-zabbix-datasource err="Unrecognized remote plugin message: \nThis usually means\n  the plugin was not compiled for this architecture,\n  the plugin is`

**Comment by konstantin-kornienko** [comment] 2023-08-29 13:50
duplicate of https://github.com/grafana/grafana-zabbix/issues/1672
current workaround - rollback to version 4.3.1

On my instance this works:
```
sudo -u grafana grafana-cli plugins install alexanderzobnin-zabbix-app 4.3.1
```

**Comment by alexanderzobnin** [comment] 2023-08-29 15:22
Closing this in favor of #1604

**Closed by alexanderzobnin** 2023-08-29 15:22 UTC
