### ISSUE TITLE
Public Dashboard Unauthorized 

### ISSUE THREAD

**Issue by kingcode94** [grafana/grafana-zabbix#1761] opened 2023-12-11 15:34 UTC
**Describe the bug**
On a public dashboard users get the error message unauthorized

**Expected behavior**
To be able to view the data with no authentication on a public dashboard

**Screenshots**
![chrome_YdMxzbYlqh](https://github.com/grafana/grafana-zabbix/assets/109674770/5965d845-db44-494e-a999-346b38df4fe8)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
|v10.2.2   |  6.4.9  | 4.4.4              |

Any help would be appreciated

**Comment by zoltanbedi** [comment] 2023-12-11 15:52
Duplicate of #1635

**Closed by zoltanbedi** 2023-12-11 15:52 UTC
