### ISSUE TITLE
Public Dashboard shows "Un-authorized" in Grafana v11.0.0

### ISSUE THREAD

**Issue by Jedi-5** [grafana/grafana-zabbix#1843] opened 2024-06-18 17:15 UTC
**Describe the bug**
- Created a dashboard, where zabbix is used as Data source (Zabbix Plugin v4.5.1 )
- Made the dashboard public >> open the public dashboard without login into Grafana
- Dashboard shows "Un-authorized" error >> "No Data" message being displayed

**Expected behavior**
Public Dashboard should work as it was working on Grafana v9.5.2

**Screenshots**
<img width="920" alt="image" src="https://github.com/grafana/grafana-zabbix/assets/8300079/e5ac246f-03f9-4a2f-8afb-eabf39ce1323">

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| -------   | ------   | ---------------------      |
|  11.0.0   |  6.2.1   |            4.5.1                  |

**Comment by zoltanbedi** [comment] 2024-06-18 20:22
Duplicate of #1635

**Closed by zoltanbedi** 2024-06-18 20:22 UTC
