### ISSUE TITLE
Error while using Plugin

### ISSUE THREAD

**Issue by lwilfredoflor** [grafana/grafana-zabbix#1717] opened 2023-10-13 03:23 UTC
ZABBIX VERSION

root@grafana:~# zabbix_server --version
zabbix_server (Zabbix) 7.0.0alpha6
Revision cf4c50ece53 4 October 2023, compilation time: Oct  4 2023 10:42:13

GRAFANA VERSION

root@grafana:~# grafana-cli -v
grafana version 10.0.3

When trying to get "PROBLEMs" from zabbix using the plugin we are getting an error

Invalid params. Invalid parameter "/output/2": value must be one of "proxyid", "name", "operating_mode", "description", "allowed_addresses", "address", "port", "tls_connect", "tls_accept", "tls_issuer", "tls_subject", "custom_timeouts", "timeout_zabbix_agent", "timeout_simple_check", "timeout_snmp_agent", "timeout_external_check", "timeout_db_monitor", "timeout_http_agent", "timeout_ssh_agent", "timeout_telnet_agent", "timeout_script", "lastaccess", "version", "compatibility".

**Comment by zoltanbedi** [comment] 2023-10-25 20:24
duplicate of #1714

**Closed by zoltanbedi** 2023-10-25 20:24 UTC
